// Managebooks.jsx

// import React, { useEffect, useState } from "react";
// import axios from "axios";
// import Navbar from "./Navbar";

// const ManageBooks = () => {
//   const [books, setBooks] = useState([]);
//   const [form, setForm] = useState({
//     authorName: "",
//     title: "",
//     genre: "",
//     publishedYear: "",
//   });
//   const [isEditing, setIsEditing] = useState(false);
//   const [editingId, setEditingId] = useState(null);
//   const [showForm, setShowForm] = useState(false);

//   // Fetch books from Open Library API
//   const fetchBooks = async (searchTitle = "the lord of the rings") => {
//     try {
//       const response = await axios.get(
//         `http://openlibrary.org/search.json?title=${searchTitle}`
//       );
//       const fetchedBooks = response.data.docs.slice(0, 10).map((book) => ({
//         id: book.key,
//         authorName: book.author_name ? book.author_name[0] : "Unknown",
//         title: book.title,
//         genre: book.subject ? book.subject[0] : "Unknown",
//         publishedYear: book.first_publish_year || "Unknown",
//       }));
//       setBooks(fetchedBooks);
//     } catch (error) {
//       console.error("Error fetching books:", error);
//     }
//   };

//   // Add a new book
//   const addBook = () => {
//     const newBook = {
//       id: Date.now().toString(),
//       ...form,
//     };
//     setBooks((prevBooks) => [...prevBooks, newBook]);
//     alert("Book added successfully!"); // Alert message
//     resetForm();
//   };

//   // Update an existing book
//   const updateBook = () => {
//     setBooks((prevBooks) =>
//       prevBooks.map((book) =>
//         book.id === editingId ? { ...book, ...form } : book
//       )
//     );
//     alert("Book updated successfully!"); // Alert message
//     resetForm();
//   };

//   // Delete a book
//   const deleteBook = (id) => {
//     setBooks((prevBooks) => prevBooks.filter((book) => book.id !== id));
//     alert("Book deleted successfully!"); // Alert message
//   };

//   // Handle form submission
//   const handleSubmit = (e) => {
//     e.preventDefault();
//     if (isEditing) {
//       updateBook();
//     } else {
//       addBook();
//     }
//   };

//   // Handle input change
//   const handleChange = (e) => {
//     const { name, value } = e.target;
//     setForm({ ...form, [name]: value });
//   };

//   // Handle edit button click
//   const handleEdit = (book) => {
//     setForm(book);
//     setIsEditing(true);
//     setEditingId(book.id);
//     setShowForm(true);
//   };

//   // Reset form and close popup
//   const resetForm = () => {
//     setForm({
//       authorName: "",
//       title: "",
//       genre: "",
//       publishedYear: "",
//     });
//     setIsEditing(false);
//     setEditingId(null);
//     setShowForm(false);
//   };

//   useEffect(() => {
//     fetchBooks();
//   }, []);

//   return (
//     <div>
//       <Navbar />

//       <div className="p-6">
//         <h1 className="text-3xl text-blue-800 font-bold mb-24 text-center">
//           Manage Books
//         </h1>
//         <button
//           onClick={() => setShowForm(true)}
//           className="bg-blue-500 text-white px-4 py-2 rounded mb-4 hover:bg-blue-600 absolute right-12 top-44"
//         >
//           Add Book
//         </button>

//         <table className="min-w-full bg-white shadow-md rounded">
//           <thead>
//             <tr className="bg-gray-200">
//               <th className="px-4 py-2">Author Name</th>
//               <th className="px-4 py-2">Title</th>
//               <th className="px-4 py-2">Genre</th>
//               <th className="px-4 py-2">Published Year</th>
//               <th className="px-4 py-2">Actions</th>
//             </tr>
//           </thead>
//           <tbody>
//             {books.map((book) => (
//               <tr key={book.id} className="border-b">
//                 <td className="px-4 py-2">{book.authorName}</td>
//                 <td className="px-4 py-2">{book.title}</td>
//                 <td className="px-4 py-2">{book.genre}</td>
//                 <td className="px-4 py-2">{book.publishedYear}</td>
//                 <td className="px-4 py-2">
//                   <button
//                     onClick={() => handleEdit(book)}
//                     className="text-blue-500 hover:text-blue-700 mr-2"
//                   >
//                     Edit
//                   </button>
//                   <button
//                     onClick={() => deleteBook(book.id)}
//                     className="text-red-500 hover:text-red-700"
//                   >
//                     Delete
//                   </button>
//                 </td>
//               </tr>
//             ))}
//           </tbody>
//         </table>

//         {/* Popup form for adding/editing books */}
//         {showForm && (
//           <div className="fixed inset-0 bg-gray-800 bg-opacity-50 flex items-center justify-center">
//             <div className="bg-white p-6 rounded shadow-md w-1/3">
//               <h2 className="text-2xl font-bold mb-4">
//                 {isEditing ? "Edit Book" : "Add Book"}
//               </h2>
//               <form onSubmit={handleSubmit}>
//                 <input
//                   type="text"
//                   name="authorName"
//                   value={form.authorName}
//                   onChange={handleChange}
//                   placeholder="Author Name"
//                   className="border p-2 w-full mb-2 rounded"
//                   required
//                 />
//                 <input
//                   type="text"
//                   name="title"
//                   value={form.title}
//                   onChange={handleChange}
//                   placeholder="Title"
//                   className="border p-2 w-full mb-2 rounded"
//                   required
//                 />
//                 <input
//                   type="text"
//                   name="genre"
//                   value={form.genre}
//                   onChange={handleChange}
//                   placeholder="Genre"
//                   className="border p-2 w-full mb-2 rounded"
//                   required
//                 />
//                 <input
//                   type="number"
//                   name="publishedYear"
//                   value={form.publishedYear}
//                   onChange={handleChange}
//                   placeholder="Published Year"
//                   className="border p-2 w-full mb-4 rounded"
//                   required
//                 />
//                 <div className="flex justify-end">
//                   <button
//                     type="button"
//                     onClick={resetForm}
//                     className="bg-gray-500 text-white px-4 py-2 rounded mr-2 hover:bg-gray-600"
//                   >
//                     Cancel
//                   </button>
//                   <button
//                     type="submit"
//                     className="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600"
//                   >
//                     {isEditing ? "Update Book" : "Add Book"}
//                   </button>
//                 </div>
//               </form>
//             </div>
//           </div>
//         )}
//       </div>
//     </div>
//   );
// };

// export default ManageBooks;
import React, { useEffect, useState } from "react";
import axios from "axios";
import Navbar from "./Navbar";

const ManageBooks = () => {
  const [books, setBooks] = useState([]);
  const [form, setForm] = useState({
    name: "",
    title: "",
    genre: "",
    publishedYear: "",
  });
  const [isEditing, setIsEditing] = useState(false);
  const [editingId, setEditingId] = useState(null);
  const [showForm, setShowForm] = useState(false);


  useEffect(() => {
    fetchBooks();
}, []);

const fetchBooks = async () => {
  try {
    const response = await axios.get("http://localhost:8080/api/books");
    console.log("Books fetched:", response.data); // Log the response to check the data structure
    // Ensure the data is an array before attempting to map over it
    if (Array.isArray(response.data)) {
      setBooks(response.data); // Assuming the response has a 'data' object containing the books
    } else {
      console.error("Data is not in expected array format");
      setBooks([]); // Fallback in case the response is not an array
    }
  } catch (error) {
    console.error("Error fetching books:", error);
    setBooks([]); // Ensure books is always an array
  }
};


  // Add a new book
  const addBook = async () => {
    try {
      const response = await axios.post("http://localhost:8080/api/books", form);
      setBooks((prevBooks) => [...prevBooks, response.data.data]);
      alert("Book added successfully!");
      resetForm();
    } catch (error) {
      console.error("Error adding book:", error);
    }
  };

  // Update an existing book
  const updateBook = async () => {
    try {
      const response = await axios.put(
        `http://localhost:8080/api/books/${editingId}`,
        form
      );
      setBooks((prevBooks) =>
        prevBooks.map((book) =>
          book.id === editingId ? { ...book, ...form } : book
        )
      );
      alert("Book updated successfully!");
      resetForm();
    } catch (error) {
      console.error("Error updating book:", error);
    }
  };

  // Delete a book
  const deleteBook = async (id) => {
    try {
      await axios.delete(`http://localhost:8080/api/books/${id}`);
      setBooks((prevBooks) => prevBooks.filter((book) => book.id !== id));
      alert("Book deleted successfully!");
    } catch (error) {
      console.error("Error deleting book:", error);
    }
  };

  // Handle form submission
  const handleSubmit = (e) => {
    e.preventDefault();
    if (isEditing) {
      updateBook();
    } else {
      addBook();
    }
  };

  // Handle input change
  const handleChange = (e) => {
    const { name, value } = e.target;
    setForm({ ...form, [name]: value });
  };

  // Handle edit button click
  const handleEdit = (book) => {
    setForm(book);
    setIsEditing(true);
    setEditingId(book.id);
    setShowForm(true);
  };

  // Reset form and close popup
  const resetForm = () => {
    setForm({
      authorName: "",
      title: "",
      genre: "",
      publishedYear: "",
    });
    setIsEditing(false);
    setEditingId(null);
    setShowForm(false);
  };

  useEffect(() => {
    fetchBooks();
  }, []);

  return (
    <div>
      <Navbar />

      <div className="p-6">
        <h1 className="text-3xl text-blue-800 font-bold mb-24 text-center">
          Manage Books
        </h1>
        <button
          onClick={() => setShowForm(true)}
          className="bg-blue-500 text-white px-4 py-2 rounded mb-4 hover:bg-blue-600 absolute right-12 top-44"
        >
          Add Book
        </button>

        <table className="min-w-full bg-white shadow-md rounded">
          <thead>
            <tr className="bg-gray-200">
            <th className="px-4 py-2">S.No</th> {/* Serial Number Column */}
              <th className="px-4 py-2">Author Name</th>
              <th className="px-4 py-2">Title</th>
              <th className="px-4 py-2">Genre</th>
              <th className="px-4 py-2">Published Year</th>
              <th className="px-4 py-2">Actions</th>
            </tr>
          </thead>
          <tbody>
  {books.length === 0 ? (
    <tr>
      <td colSpan="5" className="text-center py-4">No books available</td>
    </tr>
  ) : (
    books.map((book,index) => (
      <tr key={book.id} className="border-b">
         <th className="px-4 py-2">{index+1}</th> {/* Serial Number Column */}
        <td className="px-4 py-2">{book.authorName}</td> {/* Corrected field */}
        <td className="px-4 py-2">{book.title}</td>
        <td className="px-4 py-2">{book.genre}</td>
        <td className="px-4 py-2">{book.publishedYear}</td>
        <td className="px-4 py-2">
          <button
            onClick={() => handleEdit(book)}
            className="text-blue-500 hover:text-blue-700 mr-2"
          >
            Edit
          </button>
          <button
            onClick={() => deleteBook(book.id)}
            className="text-red-500 hover:text-red-700"
          >
            Delete
          </button>
        </td>
      </tr>
    ))
  )}
</tbody>
</table>

        {/* Popup form for adding/editing books */}
        {showForm && (
          <div className="fixed inset-0 bg-gray-800 bg-opacity-50 flex items-center justify-center">
            <div className="bg-white p-6 rounded shadow-md w-1/3">
              <h2 className="text-2xl font-bold mb-4">
                {isEditing ? "Edit Book" : "Add Book"}
              </h2>
              <form onSubmit={handleSubmit}>
                <input
                  type="text"
                  name="name"
                  value={form.authorName}
                  onChange={handleChange}
                  placeholder="Author Name"
                  className="border p-2 w-full mb-2 rounded"
                  required
                />
                <input
                  type="text"
                  name="title"
                  value={form.title}
                  onChange={handleChange}
                  placeholder="Title"
                  className="border p-2 w-full mb-2 rounded"
                  required
                />
                <input
                  type="text"
                  name="genre"
                  value={form.genre}
                  onChange={handleChange}
                  placeholder="Genre"
                  className="border p-2 w-full mb-2 rounded"
                  required
                />
                <input
                  type="number"
                  name="publishedYear"
                  value={form.publishedYear}
                  onChange={handleChange}
                  placeholder="Published Year"
                  className="border p-2 w-full mb-4 rounded"
                  required
                />
                <div className="flex justify-end">
                  <button
                    type="button"
                    onClick={resetForm}
                    className="bg-gray-500 text-white px-4 py-2 rounded mr-2 hover:bg-gray-600"
                  >
                    Cancel
                  </button>
                  <button
                    type="submit"
                    className="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600"
                  >
                    {isEditing ? "Update Book" : "Add Book"}
                  </button>
                </div>
              </form>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default ManageBooks;

// manage-books.component.ts
import { Component, OnInit } from '@angular/core';
import { BookService } from './books.service';

// Define the Book interface
interface Book {
  id: string;
  authorName: string;
  title: string;
  genre: string;
  publishedYear: string;
}

@Component({
  selector: 'managebooks',
  templateUrl: './manage-books.component.html',
  // styleUrls: ['./manage-books.component.css'],
})
export class ManageBooksComponent implements OnInit {
  books: Book[] = [];  // Ensure books are typed as an array of Book objects
  form: Omit<Book, 'id'> = {  // Ensure form doesn't require the 'id' property initially
    authorName: '',
    title: '',
    genre: '',
    publishedYear: '',
  };
  isEditing: boolean = false;
  editingId: string | null = null;
  showForm: boolean = false;

  constructor(private bookService: BookService) {}

  ngOnInit(): void {
    this.fetchBooks();
  }

  // Fetch books from Open Library API
  fetchBooks(searchTitle: string = 'the lord of the rings'): void {
    this.bookService.fetchBooks(searchTitle).subscribe((response: any) => {
      this.books = response.docs.slice(0, 10).map((book: any) => ({
        id: book.key,
        authorName: book.author_name ? book.author_name[0] : 'Unknown',
        title: book.title,
        genre: book.subject ? book.subject[0] : 'Unknown',
        publishedYear: book.first_publish_year || 'Unknown',
      }));
    });
  }

  // Add a new book
  addBook(): void {
    const newBook: Book = {
      id: Date.now().toString(),  // Ensure an id is generated when adding a new book
      ...this.form,  // Spread the form values into the new book object
    };
    this.books.push(newBook);
    alert('Book added successfully!');
    this.resetForm();
  }

  // Update an existing book
  updateBook(): void {
    this.books = this.books.map((book) =>
      book.id === this.editingId ? { ...book, ...this.form } : book
    );
    alert('Book updated successfully!');
    this.resetForm();
  }

  // Delete a book
  deleteBook(id: string): void {
    this.books = this.books.filter((book) => book.id !== id);
    alert('Book deleted successfully!');
  }

  // Handle form submission
  handleSubmit(): void {
    if (this.isEditing) {
      this.updateBook();
    } else {
      this.addBook();
    }
  }

  // Handle input changes
  handleChange(event: Event): void {  // Event is explicitly typed
    const input = event.target as HTMLInputElement;  // Cast to HTMLInputElement to access name and value
    this.form[input.name as keyof typeof this.form] = input.value;  // Safely update the form
  }

  // Handle edit button click
  handleEdit(book: Book): void {  // Ensure book parameter is typed as Book
    this.form = { ...book };  // Populate the form with the book's details
    this.isEditing = true;
    this.editingId = book.id;
    this.showForm = true;
  }

  // Reset form and close popup
  resetForm(): void {
    this.form = {
      authorName: '',
      title: '',
      genre: '',
      publishedYear: '',
    };
    this.isEditing = false;
    this.editingId = null;
    this.showForm = false;
  }
}

<div>
  <h1 class="text-3xl text-blue-800 font-bold mb-24 text-center">
    Manage Books
  </h1>
  <button
    (click)="showForm = true"
    class="bg-blue-500 text-white px-4 py-2 rounded mb-4 hover:bg-blue-600 absolute right-12 top-44"
  >
    Add Book
  </button>

  <table class="min-w-full bg-white shadow-md rounded">
    <thead>
      <tr class="bg-gray-200">
        <th class="px-4 py-2">Author Name</th>
        <th class="px-4 py-2">Title</th>
        <th class="px-4 py-2">Genre</th>
        <th class="px-4 py-2">Published Year</th>
        <th class="px-4 py-2">Actions</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let book of books" class="border-b">
        <td class="px-4 py-2">{{ book.authorName }}</td>
        <td class="px-4 py-2">{{ book.title }}</td>
        <td class="px-4 py-2">{{ book.genre }}</td>
        <td class="px-4 py-2">{{ book.publishedYear }}</td>
        <td class="px-4 py-2">
          <button
            (click)="handleEdit(book)"
            class="text-blue-500 hover:text-blue-700 mr-2"
          >
            Edit
          </button>
          <button
            (click)="deleteBook(book.id)"
            class="text-red-500 hover:text-red-700"
          >
            Delete
          </button>
        </td>
      </tr>
    </tbody>
  </table>

  <!-- Popup form for adding/editing books -->
  <div
    *ngIf="showForm"
    class="fixed inset-0 bg-gray-800 bg-opacity-50 flex items-center justify-center"
  >
    <div class="bg-white p-6 rounded shadow-md w-1/3">
      <h2 class="text-2xl font-bold mb-4">
        {{ isEditing ? 'Edit Book' : 'Add Book' }}
      </h2>
      <form (submit)="handleSubmit()">
        <input
          type="text"
          name="authorName"
          [(ngModel)]="form.authorName"
          placeholder="Author Name"
          class="border p-2 w-full mb-2 rounded"
          required
        />
        <input
          type="text"
          name="title"
          [(ngModel)]="form.title"
          placeholder="Title"
          class="border p-2 w-full mb-2 rounded"
          required
        />
        <input
          type="text"
          name="genre"
          [(ngModel)]="form.genre"
          placeholder="Genre"
          class="border p-2 w-full mb-2 rounded"
          required
        />
        <input
          type="number"
          name="publishedYear"
          [(ngModel)]="form.publishedYear"
          placeholder="Published Year"
          class="border p-2 w-full mb-4 rounded"
          required
        />
        <div class="flex justify-end">
          <button
            type="button"
            (click)="resetForm()"
            class="bg-gray-500 text-white px-4 py-2 rounded mr-2 hover:bg-gray-600"
          >
            Cancel
          </button>
          <button
            type="submit"
            class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600"
          >
            {{ isEditing ? 'Update Book' : 'Add Book' }}
          </button>
        </div>
      </form>
    </div>
  </div>
</div>
